mkdir bin
nasm -o bin/32sinst.inf src/32sinst.inf.a
nasm -o bin/32sinst.mst src/32sinst.mst.a
nasm -o bin/cards.dll src/cards.dll.a
nasm -o bin/comctl32.dll src/comctl32.dll.a
nasm -o bin/comdlg32.dll src/comdlg32.dll.a
nasm -o bin/compobj.dll src/compobj.dll.a
nasm -o bin/crtdll.dll src/crtdll.dll.a
nasm -o bin/ctype.nls src/ctype.nls.a
nasm -o bin/freecell.exe src/freecell.exe.a
nasm -o bin/freecell.hlp src/freecell.hlp.a
nasm -o bin/ftsrch.dll src/ftsrch.dll.a
nasm -o bin/iniupd.dll src/iniupd.dll.a
nasm -o bin/l_intl.nls src/l_intl.nls.a
nasm -o bin/locale.nls src/locale.nls.a
nasm -o bin/l_trk.nls src/l_trk.nls.a
nasm -o bin/lz32.dll src/lz32.dll.a
nasm -o bin/mscomstf.dll src/mscomstf.dll.a
nasm -o bin/mscuistf.dll src/mscuistf.dll.a
nasm -o bin/msdetect.inc src/msdetect.inc.a
nasm -o bin/msdetstf.dll src/msdetstf.dll.a
nasm -o bin/msinsstf.dll src/msinsstf.dll.a
nasm -o bin/_mssetup.exe src/_mssetup.exe.a
nasm -o bin/msshlstf.dll src/msshlstf.dll.a
nasm -o bin/_mstest.exe src/_mstest.exe.a
nasm -o bin/msuilstf.dll src/msuilstf.dll.a
nasm -o bin/netapi32.dll src/netapi32.dll.a
nasm -o bin/ntmsg.dll src/ntmsg.dll.a
nasm -o bin/ole2conv.dll src/ole2conv.dll.a
nasm -o bin/ole2disp.dll src/ole2disp.dll.a
nasm -o bin/ole2.dll src/ole2.dll.a
nasm -o bin/ole2nls.dll src/ole2nls.dll.a
nasm -o bin/ole2prox.dll src/ole2prox.dll.a
nasm -o bin/ole2.reg src/ole2.reg.a
nasm -o bin/ole2thk.dll src/ole2thk.dll.a
nasm -o bin/ole32.dll src/ole32.dll.a
nasm -o bin/oleaut32.dll src/oleaut32.dll.a
nasm -o bin/olecli32.dll src/olecli32.dll.a
nasm -o bin/olecli.dll src/olecli.dll.a
nasm -o bin/oledlg.dll src/oledlg.dll.a
nasm -o bin/olesvr32.dll src/olesvr32.dll.a
nasm -o bin/p_037.nls src/p_037.nls.a
nasm -o bin/p_10000.nls src/p_10000.nls.a
nasm -o bin/p_10001.nls src/p_10001.nls.a
nasm -o bin/p_10006.nls src/p_10006.nls.a
nasm -o bin/p_10007.nls src/p_10007.nls.a
nasm -o bin/p_10029.nls src/p_10029.nls.a
nasm -o bin/p_10079.nls src/p_10079.nls.a
nasm -o bin/p_10081.nls src/p_10081.nls.a
nasm -o bin/p_1026.nls src/p_1026.nls.a
nasm -o bin/p_1250.nls src/p_1250.nls.a
nasm -o bin/p_1251.nls src/p_1251.nls.a
nasm -o bin/p_1252.nls src/p_1252.nls.a
nasm -o bin/p_1253.nls src/p_1253.nls.a
nasm -o bin/p_1254.nls src/p_1254.nls.a
nasm -o bin/p_437.nls src/p_437.nls.a
nasm -o bin/p_500.nls src/p_500.nls.a
nasm -o bin/p_737.nls src/p_737.nls.a
nasm -o bin/p_850.nls src/p_850.nls.a
nasm -o bin/p_852.nls src/p_852.nls.a
nasm -o bin/p_855.nls src/p_855.nls.a
nasm -o bin/p_857.nls src/p_857.nls.a
nasm -o bin/p_860.nls src/p_860.nls.a
nasm -o bin/p_861.nls src/p_861.nls.a
nasm -o bin/p_863.nls src/p_863.nls.a
nasm -o bin/p_865.nls src/p_865.nls.a
nasm -o bin/p_866.nls src/p_866.nls.a
nasm -o bin/p_869.nls src/p_869.nls.a
nasm -o bin/p_875.nls src/p_875.nls.a
nasm -o bin/p_932.nls src/p_932.nls.a
nasm -o bin/p_936.nls src/p_936.nls.a
nasm -o bin/p_949.nls src/p_949.nls.a
nasm -o bin/p_950.nls src/p_950.nls.a
nasm -o bin/riched32.dll src/riched32.dll.a
nasm -o bin/sck16thk.dll src/sck16thk.dll.a
nasm -o bin/setupapi.inc src/setupapi.inc.a
nasm -o bin/setup.exe src/setup.exe.a
nasm -o bin/setup.lst src/setup.lst.a
nasm -o bin/shell32.dll src/shell32.dll.a
nasm -o bin/sortkey.nls src/sortkey.nls.a
nasm -o bin/sorttbls.nls src/sorttbls.nls.a
nasm -o bin/stdole32.tlb src/stdole32.tlb.a
nasm -o bin/stdole.tlb src/stdole.tlb.a
nasm -o bin/storage.dll src/storage.dll.a
nasm -o bin/typelib.dll src/typelib.dll.a
nasm -o bin/unicode.nls src/unicode.nls.a
nasm -o bin/version.dll src/version.dll.a
nasm -o bin/w32s.386 src/w32s.386.a
nasm -o bin/w32scomb.dll src/w32scomb.dll.a
nasm -o bin/w32skrnl.dll src/w32skrnl.dll.a
nasm -o bin/w32sys.dll src/w32sys.dll.a
nasm -o bin/win32s16.dll src/win32s16.dll.a
nasm -o bin/win32s.exe src/win32s.exe.a
nasm -o bin/windows.hlp src/windows.hlp.a
nasm -o bin/winhlp32.cnt src/winhlp32.cnt.a
nasm -o bin/winhlp32.exe src/winhlp32.exe.a
nasm -o bin/winhlp32.hlp src/winhlp32.hlp.a
nasm -o bin/winmm16.dll src/winmm16.dll.a
nasm -o bin/winmm.dll src/winmm.dll.a
nasm -o bin/winspool.drv src/winspool.drv.a
nasm -o bin/wsock32.dll src/wsock32.dll.a
sha1sum -c win32s.sha1
